/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./global-setting/block.vue')['default']
    Breadcrumb: typeof import('./breadcrumb/index.vue')['default']
    Chart: typeof import('./chart/index.vue')['default']
    Footer: typeof import('./footer/index.vue')['default']
    FormWrapper: typeof import('./global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./global-setting/index.vue')['default']
    List: typeof import('./message-box/list.vue')['default']
    Menu: typeof import('./menu/index.vue')['default']
    MessageBox: typeof import('./message-box/index.vue')['default']
    Navbar: typeof import('./navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sounder: typeof import('./sounder/index.vue')['default']
    TabBar: typeof import('./tab-bar/index.vue')['default']
    TabItem: typeof import('./tab-bar/tab-item.vue')['default']
  }
}
