name: View CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Asia/Shanghai
  BUILD_GREETING: hello
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        node-version: [ 20 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # pull代码
      - name: Print timezone info
        run: |
          date
          timedatectl
          . scripts/cicd/funcs.sh
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: set -evx && pnpm i && pnpm run prd
      - name: Setup SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_KEY: a2cd
        run: setup_ssh
      - name: Run deploy
        run: sync_files && reload_nginx
